In [12]:
from urllib.request import urlopen
import numpy as np

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
our_data = np.genfromtxt(url, delimiter=",", usecols=(0,1,2,3), dtype=float)
our_data


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
#3
print("Our mean->", np.mean(our_data[:, 0]))
print("Our median->", np.median(our_data[:, 0]))
print("Our std->", np.std(our_data[:, 0]))



Our mean-> 5.843333333333334
Our median-> 5.8
Our std-> 0.8253012917851409


In [13]:
#4
flat_indices = np.arange(our_data.size)
np.random.shuffle(flat_indices)
flat_indices = flat_indices[:20]
row_indices, col_indices = np.unravel_index(flat_indices, our_data.shape)
our_data[row_indices, col_indices] = np.nan
nan_count = np.count_nonzero(np.isnan(our_data))
our_data, nan_count




(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, nan],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, nan],
        [4.6, 3.6, 1. , nan],
        [5.1, 3.3, nan, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [nan, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [14]:
#5
np.sum(np.isnan(our_data[:, 0]))

7

In [17]:
#6
filtered_list = []
filtered_data = our_data[(our_data[:, 2] > 1.5) & (our_data[:, 0] < 5)]
filtered_data


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [18]:
#7
filtered_data = np.nan_to_num(filtered_data)
filtered_data

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [19]:
#8
print(np.unique(filtered_data, return_counts=True))

(array([0.2, 1. , 1.6, 1.7, 1.9, 2.4, 2.5, 3.2, 3.3, 3.4, 4.5, 4.7, 4.8,
       4.9]), array([3, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2]))


In [20]:
#9
first_part = filtered_data[:len(filtered_data)//2]
second_part = filtered_data[len(filtered_data)//2:]
first_part, second_part

(array([[4.8, 3.4, 1.6, 0.2],
        [4.8, 3.4, 1.9, 0.2]]),
 array([[4.7, 3.2, 1.6, 0.2],
        [4.9, 2.4, 3.3, 1. ],
        [4.9, 2.5, 4.5, 1.7]]))

In [21]:
#10
first_part = first_part[first_part[:, 0].argsort()]
second_part = second_part[second_part[:, 0].argsort()[::-1]]
first_part, second_part

(array([[4.8, 3.4, 1.6, 0.2],
        [4.8, 3.4, 1.9, 0.2]]),
 array([[4.9, 2.5, 4.5, 1.7],
        [4.9, 2.4, 3.3, 1. ],
        [4.7, 3.2, 1.6, 0.2]]))

In [37]:
#11
united_data = np.vstack((first_part, second_part))
united_data

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.9, 2.5, 4.5, 1.7],
       [4.9, 2.4, 3.3, 1. ],
       [4.7, 3.2, 1.6, 0.2]])

In [24]:
#12
flatten_data = united_data.flatten()
unique_numbers, counts = np.unique(flatten_data, return_counts=True)
unique_numbers[np.argmax(counts)]

0.2

In [38]:
#13,14
def mult_below_adjusted_mean(col):
    mean_value = np.mean(col)
    less_than_mean = col < mean_value
    col[less_than_mean] *= 2
    col[~less_than_mean] /= 4


mult_below_adjusted_mean(united_data[:, 2])
united_data

array([[4.8  , 3.4  , 3.2  , 0.2  ],
       [4.8  , 3.4  , 3.8  , 0.2  ],
       [4.9  , 2.5  , 1.125, 1.7  ],
       [4.9  , 2.4  , 0.825, 1.   ],
       [4.7  , 3.2  , 3.2  , 0.2  ]])