In [3]:
#1
import re
import urllib.request

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"


with urllib.request.urlopen(url) as response:
    iris_data = re.sub(r'[^\d.,\n]', '', response.read().decode('utf-8')).strip()

print(iris_data)

5.1,3.5,1.4,0.2,
4.9,3.0,1.4,0.2,
4.7,3.2,1.3,0.2,
4.6,3.1,1.5,0.2,
5.0,3.6,1.4,0.2,
5.4,3.9,1.7,0.4,
4.6,3.4,1.4,0.3,
5.0,3.4,1.5,0.2,
4.4,2.9,1.4,0.2,
4.9,3.1,1.5,0.1,
5.4,3.7,1.5,0.2,
4.8,3.4,1.6,0.2,
4.8,3.0,1.4,0.1,
4.3,3.0,1.1,0.1,
5.8,4.0,1.2,0.2,
5.7,4.4,1.5,0.4,
5.4,3.9,1.3,0.4,
5.1,3.5,1.4,0.3,
5.7,3.8,1.7,0.3,
5.1,3.8,1.5,0.3,
5.4,3.4,1.7,0.2,
5.1,3.7,1.5,0.4,
4.6,3.6,1.0,0.2,
5.1,3.3,1.7,0.5,
4.8,3.4,1.9,0.2,
5.0,3.0,1.6,0.2,
5.0,3.4,1.6,0.4,
5.2,3.5,1.5,0.2,
5.2,3.4,1.4,0.2,
4.7,3.2,1.6,0.2,
4.8,3.1,1.6,0.2,
5.4,3.4,1.5,0.4,
5.2,4.1,1.5,0.1,
5.5,4.2,1.4,0.2,
4.9,3.1,1.5,0.1,
5.0,3.2,1.2,0.2,
5.5,3.5,1.3,0.2,
4.9,3.1,1.5,0.1,
4.4,3.0,1.3,0.2,
5.1,3.4,1.5,0.2,
5.0,3.5,1.3,0.3,
4.5,2.3,1.3,0.3,
4.4,3.2,1.3,0.2,
5.0,3.5,1.6,0.6,
5.1,3.8,1.9,0.4,
4.8,3.0,1.4,0.3,
5.1,3.8,1.6,0.2,
4.6,3.2,1.4,0.2,
5.3,3.7,1.5,0.2,
5.0,3.3,1.4,0.2,
7.0,3.2,4.7,1.4,
6.4,3.2,4.5,1.5,
6.9,3.1,4.9,1.5,
5.5,2.3,4.0,1.3,
6.5,2.8,4.6,1.5,
5.7,2.8,4.5,1.3,
6.3,3.3,4.7,1.6,
4.9,2.4,3.3,1.0,
6.6,2.9,4.6,1.

In [4]:
#2
import numpy as np
iris_list = iris_data.split("\n")
data_list = [list(map(float, line[:len(line)-1].split(","))) for line in iris_list]
our_data = np.array(data_list)
print(our_data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
#3
print("Our mean->", np.mean(our_data[:, 0]))
print("Our median->", np.median(our_data[:, 0]))
print("Our std->", np.std(our_data[:, 0]))



Our mean-> 5.843333333333334
Our median-> 5.8
Our std-> 0.8253012917851409


In [6]:
#4
coordinates = []
rows, cols = our_data.shape
for i in range(20):
     while True:
        random_cords = (np.random.randint(rows), np.random.randint(cols))
        if random_cords not in coordinates:
            coordinates.append(random_cords)
            break
for pair in coordinates:
    our_data[pair[0]][pair[1]] = np.nan
print(our_data)
print(np.sum(np.isnan(our_data)))




[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 nan 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [nan 3.3 1.7 nan]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 nan]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [nan 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [7]:
#5
print(np.sum(np.isnan(our_data[:, 0])))

5


In [8]:
#6
filtered_list = []
for line in our_data:
    if line[2]>1.5 and line[0]<5:
        filtered_list.append(line)
filtered_data = np.array(filtered_list)
print(filtered_data)


[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [9]:
#7
filtered_data = np.nan_to_num(filtered_data)
print(filtered_data)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [10]:
#8
print(np.unique(filtered_data, return_counts=True))

(array([0.2, 1. , 1.6, 1.7, 1.9, 2.4, 2.5, 3.1, 3.2, 3.3, 3.4, 4.5, 4.7,
       4.8, 4.9]), array([4, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 3, 2]))


In [19]:
#9
first_part = filtered_data[:len(filtered_data)//2]
second_part = filtered_data[len(filtered_data)//2:]
print(first_part)
print(second_part)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]]
[[4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [21]:
#10
first_part = first_part[first_part[:, 0].argsort()]
print(first_part)
second_part = second_part[second_part[:, 0].argsort()[::-1]]
print(second_part)

[[4.7 3.2 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]]
[[4.9 2.5 4.5 1.7]
 [4.9 2.4 3.3 1. ]
 [4.8 3.1 1.6 0.2]]


In [23]:
#11
united_data = np.vstack((first_part, second_part))
print(united_data)

[[4.7 3.2 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.9 2.5 4.5 1.7]
 [4.9 2.4 3.3 1. ]
 [4.8 3.1 1.6 0.2]]


In [32]:
#12
flatten_data = united_data.flatten()
unique_numbers, counts = np.unique(flatten_data, return_counts=True)
print(unique_numbers[np.argmax(counts)])

0.2


In [36]:
#13,14
def mult_below_adjusted_mean(col):
    print(np.mean(col))
    for idx, element in enumerate(col):
        if element < np.mean(col):
            element *= 2
        else:
            element /= 4
        col[idx] = element


mult_below_adjusted_mean(united_data[:, 2])
print(united_data)

2.4166666666666665
[[4.7   3.2   3.2   0.2  ]
 [4.8   3.4   3.2   0.2  ]
 [4.8   3.4   3.8   0.2  ]
 [4.9   2.5   1.125 1.7  ]
 [4.9   2.4   0.825 1.   ]
 [4.8   3.1   3.2   0.2  ]]
